### ISSUE TITLE
Syntax error (environ)

### ISSUE THREAD

**Issue by Keshav2136** [WhoisMari/BidWars#1]
![github code review](https://user-images.githubusercontent.com/13808150/131688301-38633884-1f2d-4705-a744-c8011e9ab568.png)

**Error at line 114 after installing environ package**
```
File "/BidWars/bidwars/lib/python3.9/site-packages/environ.py", line 114
    raise ValueError, "No frame marked with %s." % fname

SyntaxError: invalid syntax
```

_I started a virtualenv and installed django and environ to run your code._

If you can do:
1. Create a requirements.txt file using  `pip3 freeze > requirements.txt`  to include all your dependencies
2. Check out this: https://stackoverflow.com/questions/31684375/automatically-create-requirements-txt

**Comment by WhoisMari** [comment]
Hey @Keshav2136!

You're right, thanks for pointing that out! 

I've pushed the requirements.txt file and added some instructions on how to run this project. 

I hope that helps! :)

Please let me know if you experience any other issues. Thanks again!
